version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8099:8099"
    volumes:
      - ".:/app"
    depends_on:
      - postgres
  
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: "bank_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password123"
    ports:
      - "10001:5432"
      